### PR TITLE
Tech updates

### PR DESCRIPTION
**Pull request by rromanovsky**
1. Update dev environment
2. Dynamically get the list of available formatter versions on server start
3. Generate the default configs for all styles

### CODE REVIEW

**Comment by Skim-x-CAT** [comment]
Do some checks before merging - part of the script that checks available clang-versions is broken right now. Will look later this week.

**Comment by zed0** [comment]
These have been merged along with a change to serve the frontend from the server, which should solve #14.

Thanks very much for these changes, much appreciated.

**Comment by zed0** [comment]
@Skim-x-CAT @rromanovsky Do you mind being added to the authors list?

**Comment by rromanovsky** [comment]
@zed0 Sure I don't mind thanks! 😇 
But as @Skim-x-CAT has mentioned we need to do some additional fixes for this pull request further

**Comment by zed0** [comment]
I'm not sure what the issue was with the setup script.  I ran it a couple of time and sometimes it seemed not to download the source files, but I haven't managed to work out why yet.
However it worked sufficiently often for me to update the main site.

**Comment by Skim-x-CAT** [comment]
@zed0 Glad that this worked for you. Still @rromanovsky promised to make changes to fix #17 
And, yes, I don't mind.

**Pull request merged**
